### ISSUE TITLE
Failing with Gerbers output from OrCad

### ISSUE THREAD

**Issue by alexgoldstone** [tracespace/pcb-stackup#19]
Thank you for your very quick fix to the `gerber-to-svg` project. I have since discovered this `pcb-stackup` project and tried running the same files through using the sample code from the README and changing `gerberPaths` to point to my gerber files.

The output I get is:

```
node_modules/pcb-stackup/lib/sort-layers.js:9
var side = type[0]
               ^

TypeError: Cannot read property '0' of undefined
```

Since this is a different project, I have attached the same Gerber files here as an example.
[KB0006R00.zip](https://github.com/tracespace/pcb-stackup/files/356145/KB0006R00.zip)

**Comment by mcous** [comment]
The latest release of pcb-stackup is a little behind gerber-to-svg and whats-that-gerber right now. pcb-stackup is using v1 of both of those modules, but their latests are up to v2. You're getting that error because you've installed the latest of whats-that-gerber instead of v1.

To use the currently released version of pcb-stackup, you'll need to install `gerber-to-svg@1` and `whats-that-gerber@1` as specified in peerDependencies in `package.json`. Alternatively, until #12 is merged and pcb-stackup becomes a lot easier, you can check out [pcb-stackup-core](https://github.com/tracespace/pcb-stackup-core), which uses `gerber-to-svg@latest` and `whats-that-gerber@latest`
